########################################
# Environment variables
# if you happy and you know it clap your hands?
########################################

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots
env = QT_QPA_PLATFORM,xcb
env = QT_STYLE_OVERRIDE,kvantum
env = XDG_MENU_PREFIX,arch-
env = QT_QPA_PLATFORMTHEME,qt5ct
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = XDG_SESSION_TYPE,wayland
env = XDG_CURRENT_DESKTOP,MangoWC
