# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

# window rule
#windowrule=isfloating:1,appid:com.danklinux.dms

# fsearch scratchpad
windowrule=isnamedscratchpad:1,title:FSearch,appid:io.github.cboxdoerfer.FSearch


# copyq
windowrule=isfloating:1,appid:com.github.hluk.copyq
