#################
### AUTOSTART ###
#################

# --- 1. Environment & Essential Bridges ---
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = xrdb -load ~/.config/X11/Xresources
exec-once = systemctl --user start hyprpolkitagent
exec-once = gnome-keyring-daemon --start --components=secrets,ssh,pkcs11

# --- 2. Desktop Shell (Dank Material Shell) ---
#exec-once = QT_QPA_PLATFORM=wayland dms run -d
#exec-once = noctalia -d

# --- 3. System Services & Background Daemons ---
exec-once = walker --gapplication-service
exec-once = kdeconnect-indicator
exec-once = udiskie -t -f nemo
exec-once = appimagelauncherd
exec-once = playerctld
exec-once = wayvnc -o "HDMI-A-1"
exec-once = copyq
exec-once = eww daemon
exec-once = awww-daemon
#exec-once = sleep 2 && eww open-many bar_0 bar_1


# --- 4. Apps (Start in background/tray) ---
exec-once = sleep 5 && persepolis --tray
exec-once = sleep 5 && qbittorrent
exec-once = sleep 5 && antimicrox --tray
exec-once = sleep 5 && easyeffects --service-mode
exec-once = sleep 5 && variety

# --- 5. Custom Scripts,  Watchers, widgets ---
exec-once = file-watcher --daemon
