# --- COLORS ---
color0 #161925
color1 #e6133e
color2 #00e8c6
color3 #cc5500
color4 #0096b1
color5 #c50ed2
color6 #06d6a0
color7 #c3c7d1
color8 #6d707b
color9 #ff3b5c
color10 #33f0d4
color11 #e6681a
color12 #1cb1cc
color13 #dd3ee8
color14 #36e8b4
color15 #fefefe

cursor                #c50ed2
cursor_text_color     #fefefe
background            #161925
foreground            #c3c7d1
selection_foreground  #fefefe
selection_background  #c50ed2
active_border_color   #c50ed2
inactive_border_color #181b28
url_color             #c50ed2

active_tab_foreground   #fefefe
active_tab_background   #c50ed2
inactive_tab_foreground #c3c7d1
inactive_tab_background #181b28
cursor_trail_color      #c3c7d1


# --- WINDOW LAYOUT ---
window_padding_width 5 0
confirm_os_window_close 0
# This matches your eww widgets' "glass" look
background_opacity 0.9

# --- FONT ---
font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        11.0

# --- TABS ---
tab_bar_style           fade
tab_fade                0.25 0.5 0.75 1
active_tab_foreground   #1a1b26
active_tab_background   #7aa2f7
inactive_tab_foreground #787c99
inactive_tab_background #16161e

# --- CURSOR ---
cursor                  #c0caf5
cursor_text_color       #1a1b26
cursor_shape            beam
cursor_beam_thickness   1.5
# Makes the cursor feel "vibrant"
cursor_blink_interval   0.5
