# More option see https://github.com/DreamMaoMao/mango/wiki/

source=~/.config/mango/conf.d/environment.conf
source=~/.config/mango/conf.d/monitors.conf
source=~/.config/mango/conf.d/input.conf
source=~/.config/mango/conf.d/animation.conf
source=~/.config/mango/conf.d/layout.conf
source=~/.config/mango/conf.d/overview.conf
source=~/.config/mango/conf.d/keybinds.conf
source=~/.config/mango/conf.d/misc.conf
source=~/.config/mango/conf.d/appearance.conf
source=~/.config/mango/conf.d/rules.conf
source=~/.config/mango/conf.d/startup.conf
